language: python
env:
  matrix:
    - TOXENV=py26-pytest28
    - TOXENV=py26-pytest29
    - TOXENV=py27-pytest28
    - TOXENV=py27-pytest29
    - TOXENV=py33-pytest28
    - TOXENV=py33-pytest29
    - TOXENV=py34-pytest28
    - TOXENV=py34-pytest29
    - TOXENV=pypy-pytest28
    - TOXENV=pypy-pytest29
    - TOXENV=pypy3-pytest28
    - TOXENV=pypy3-pytest29
    - TOXENV=flake8
install:
  - pip install virtualenv==15.0.1
  - pip install tox
script:
  - VIRTUALENV_DOWNLOAD=no tox
